apiVersion: v1
kind: Pod
metadata: 
  name: webserver
  labels: 
    env: production
    owner: ahmadmohey
    webServer: nginx
    country: EG
spec:
  containers:
    - name: nginx
      image: nginx:1.21.4
      ports:
        - containerPort: 80